apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: dk32jlkjf-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe-java-quarkus:a398cc14427681906bc1bcb69f563ad862aab44b@sha256:8cc2e239af6d1e88bc1660332b4c39ef59b52cf8340113903119e7cdf281510b
        name: container-image  
